-- =====================================================================
-- Resource Booking System - PostgreSQL - STEP 2: schema
-- Run as the application role against the application database:
--   psql -U booking_app -d booking_db -f db/postgresql/02_schema.sql
-- Idempotent: safe to re-run.
-- =====================================================================

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL,
    password   VARCHAR(100) NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'USER'))
);

-- ---------------------------------------------------------------------
-- resources
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    type        VARCHAR(20)  NOT NULL,
    description VARCHAR(500),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6),
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    CONSTRAINT uk_resources_name UNIQUE (name),
    CONSTRAINT ck_resources_type CHECK (type IN ('ROOM', 'VEHICLE', 'EQUIPMENT'))
);

CREATE INDEX IF NOT EXISTS ix_resources_type   ON resources (type);
CREATE INDEX IF NOT EXISTS ix_resources_active ON resources (active);

-- ---------------------------------------------------------------------
-- reservations
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reservations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT        NOT NULL,
    user_id     BIGINT        NOT NULL,
    start_time  TIMESTAMP(6)  NOT NULL,
    end_time    TIMESTAMP(6)  NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    price       DECIMAL(10,2) NOT NULL,
    created_at  TIMESTAMP(6)  NOT NULL,
    updated_at  TIMESTAMP(6),
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    CONSTRAINT fk_reservations_resource FOREIGN KEY (resource_id) REFERENCES resources (id),
    CONSTRAINT fk_reservations_user     FOREIGN KEY (user_id)     REFERENCES users (id),
    CONSTRAINT ck_reservations_status   CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_reservations_period   CHECK (end_time > start_time),
    CONSTRAINT ck_reservations_price    CHECK (price >= 0)
);

CREATE INDEX IF NOT EXISTS ix_reservations_user     ON reservations (user_id);
CREATE INDEX IF NOT EXISTS ix_reservations_resource ON reservations (resource_id);
CREATE INDEX IF NOT EXISTS ix_reservations_status   ON reservations (status);
CREATE INDEX IF NOT EXISTS ix_reservations_period   ON reservations (resource_id, start_time, end_time);

-- ---------------------------------------------------------------------
-- refresh_tokens (opaque token, only the SHA-256 hash is stored)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------
-- audit_logs
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor          VARCHAR(50),
    action         VARCHAR(60)  NOT NULL,
    entity_type    VARCHAR(40),
    entity_id      VARCHAR(40),
    event_time     TIMESTAMP(6) NOT NULL,
    correlation_id VARCHAR(64)
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_actor  ON audit_logs (actor);
CREATE INDEX IF NOT EXISTS ix_audit_logs_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS ix_audit_logs_time   ON audit_logs (event_time);
